name: marp-to-pdf-release
concurrency: marp-to-pdf-release
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy images
        run: mkdir build && cp -R img build/img

      - name: Marp Build (README) - PDF
        uses: docker://marpteam/marp-cli:latest
        with:
          args: README.md -o build/slides.pdf
        env:
          MARP_USER: root:root

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::Build-$(date +"%Y.%m.%d_%H-%M")"

      - name: Release user firmware
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            build/slides.pdf
